# This is a basic workflow to help you get started with Actions

name: CI


on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3

      
      - name: Run a one-line script
        run: |
         echo Hello, world!
         echo "the github workspace is ${{ github.workspace}}"

     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Zip Release
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        uses: TheDoctor0/zip-release@0.7.1
        with:
         type: 'zip'
         filename: 'release.zip'
         
        run: |
         
         echo "the github zip is {{ $INPUT_FILENAME}}"
"

          
