# This is a basic workflow to help you get started with Actions

name: CI


on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: ${{github.workspace}}
          dest: result1.zip
      - name: push
        uses: actions-x/commit@v6
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result1.zip
          
      - name: push
        uses: actions-x/commit@v6
        with:
          name: GitHub Actions Autocommitter
          branch: main
          files: result1.zip
          repository: https://github.com/kjs2021/maven.git
          token: ${{ github.token }}
          force: true
         

       
     
      


          
