# This is a basic workflow to help you get started with Actions

name: CI


on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name kjs2021
          git config user.email kksaini6@yahoo.com
          git add .
          git commit -m "generated"
          git push

      
      - name: Run a one-line script
        run: |
         echo Hello, world!
         echo "the github workspace is ${{ github.workspace}}"

     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
     
    
     
      


          
